name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.17.0, 10.16.3, 12.16.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test:coverage:ci

    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        file: coverage/coverage.json
        fail_ci_if_error: false